server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/work?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver


  thymeleaf:
    prefix: classpath:/templates/
    encoding: UTF-8
    cache: false
    suffix: .html
    servlet:
      content-type: text/html

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: active
      logic-not-delete-value: 1
      logic-delete-value: 0
