server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://1.117.62.143:33061/work?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=true
    username: work
    password: C3YWsLJMcWLBNP87
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      idle-timeout: 600000
      max-lifetime: 1800000



  thymeleaf:
    prefix: classpath:/templates/
    encoding: UTF-8
    cache: false
    suffix: .html
    servlet:
      content-type: text/html

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: active
      logic-not-delete-value: 1
      logic-delete-value: 0
