server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://1.117.62.143:33061/work?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=true
    username: work
    password: C3YWsLJMcWLBNP87
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000   #不能小于30秒，否则默认回到1800秒
      connection-test-query: SELECT 1



  thymeleaf:
    prefix: classpath:/templates/
    encoding: UTF-8
    cache: false
    suffix: .html
    servlet:
      content-type: text/html

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: active
      logic-not-delete-value: 1
      logic-delete-value: 0
